### ISSUE TITLE
[Back] 예외처리, 응답값 형태 수정, gPRC 연동 fix/exception-grpc

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/ArtCore-Go#6]
### 📌 Description

예외 처리를 수정합니다. 응답값 수정에 따른 gRPC 연동을 수정합니다.

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- error 메시지 관리
- gRPC 수정
- 로딩 gif 연동
- TTS 연동

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [ ] error 메시지 통합
- [ ] gRPC 수정(응답값에 맞춰서 - 카톡 확인)
- [ ] 로딩 gif gRPC 연동
- [ ] TTS gRPC 연동
- [ ] logging 연동
